#!/bin/bash
ip tuntap add dev tun3 mode tun
echo "ip tuntap add dev tun3 mode tun [OK]"
ip link set tun3 up
echo "ip link set tun3 up [OK]"
ip addr add 10.122.101.2/30 dev tun3
echo "ip addr add 10.122.101.2/30 dev tun3"
echo "Running simpletun client on 192.168.18.133..."
./simpletun -i tun3 -c 192.168.18.133 &
echo "Simpletun client is ready"
route n
